version: "3.1"
services:
  # ------------------------------------------------------------
  # Redis cache
  # ------------------------------------------------------------
  redis:
    image: redis:5.0.5-alpine
    restart: always
    hostname: ${REDIS_HOSTNAME}
    ports:
      - ${REDIS_PORT}
    networks:
      - backend

  # ------------------------------------------------------------
  # MariaDB database
  # ------------------------------------------------------------
  db:
    image: mariadb:10.4.4-bionic
    restart: always
    hostname: ${DB_HOSTNAME}
    volumes:
      - db_data:/var/lib/mysql:delegated
      - ./conf/my.cnf:/etc/mysql/conf.d/zzz-overrides.cnf:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - backend

  # ------------------------------------------------------------
  # Apache web server
  # ------------------------------------------------------------
  apache:
    build: ./apache
    restart: always
    ports:
      - ${APACHE_PORT}:80
      - ${APACHE_PORT_SECURE}:443
    networks:
      backend:
        aliases:
          - ${SUSHI_HOSTNAME}
          - ${INVENTORY_API_HOSTNAME}
    environment:
      - SSL_CERT_FILE=${SSL_CERT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
      - SSL_CHAIN_FILE=${SSL_CHAIN_FILE}
      - SUSHI_HOSTNAME=${SUSHI_HOSTNAME}
      - SUSHI_PORT=${SUSHI_PORT}
      - SUSHI_CONTAINER_NAME=${SUSHI_CONTAINER_NAME}
      - INVENTORY_API_HOSTNAME=${INVENTORY_API_HOSTNAME}
      - INVENTORY_API_PORT=${INVENTORY_API_PORT}
      - INVENTORY_API_CONTAINER_NAME=${INVENTORY_API_CONTAINER_NAME}
    volumes:
      - ${SUSHI_PATH}:/usr/local/apache2/htdocs/sushi:delegated
      - ${INVENTORY_API_PATH}:/usr/local/apache2/htdocs/inventory-api:delegated
      - ${SSL_CERT_PATH}/${SSL_CERT_FILE}:/etc/apache2/ssl/${SSL_CERT_FILE}:delegated
      - ${SSL_CERT_PATH}/${SSL_KEY_FILE}:/etc/apache2/ssl/${SSL_KEY_FILE}:delegated
      - ${SSL_CERT_PATH}/${SSL_CHAIN_FILE}:/etc/apache2/ssl/${SSL_CHAIN_FILE}:delegated
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:delegated
      - ./conf/vhosts:/usr/local/apache2/conf/conf.d:delegated

  # ------------------------------------------------------------
  # Sushi ERP app
  # ------------------------------------------------------------
  sushi:
    image: php7.4
    environment:
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}
      - DATABASE_NAME=${SUSHI_DB_NAME}
      - DATABASE_HOSTNAME=${DB_HOSTNAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - INVENTORY_API_HOSTNAME=${INVENTORY_API_HOSTNAME}
      - INVENTORY_API_PORT=${INVENTORY_API_PORT}
      - INVENTORY_API_KEY=${INVENTORY_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - AWS_SES_DOMAIN=${AWS_SES_DOMAIN}
      - AWS_SES_REGION={$AWS_SES_REGION}
      - AWS_SES_API_KEY={$AWS_SES_API_KEY}
      - AWS_SES_SECRET_KEY={$AWS_SES_SECRET_KEY}
      - AWS_S3_REGION={$AWS_S3_REGION}
      - AWS_S3_API_KEY={$AWS_S3_API_KEY}
      - AWS_S3_SECRET_KEY={$AWS_S3_SECRET_KEY}
      - AWS_S3_BUCKET={$AWS_S3_BUCKET}
      - PUSHER_APP_ID={$PUSHER_APP_ID}
      - PUSHER_API_KEY={$PUSHER_API_KEY}
      - PUSHER_SECRET_KEY={$PUSHER_SECRET_KEY}
    networks:
      - backend
    volumes:
      - ${SUSHI_PATH}:/usr/local/apache2/htdocs/sushi:delegated
      - ./conf/php.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini:delegated
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-overrides.conf:delegated
    depends_on:
      - db
      - apache

  # ------------------------------------------------------------
  # Inventory app
  # ------------------------------------------------------------
  inventory-api:
    image: php7.4
    environment:
      - DB_DATABASE=${INVENTORY_API_DB_NAME}
      - DB_HOST=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    hostname: ${INVENTORY_API_CONTAINER_NAME}
    networks:
      - backend
    volumes:
      - ${INVENTORY_API_PATH}:/usr/local/apache2/htdocs/inventory-api:delegated
      - ./php/conf/php.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini:delegated
      - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-overrides.conf:delegated
    depends_on:
      - db
      - apache

volumes:
  db_data: {}
networks:
  backend: